<h1>IMPORTANDO LIBRERIA NUMPY </h1>

In [11]:
import numpy as np

<h4>lista de 10 elementos</h4>

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array
<h5 style="color:#12A6E8 ">array: arreglo</h5>

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h4>tipo de estructura </h4>


In [12]:
type(arreglo)

numpy.ndarray

<h4> tipo de datos del arreglo </h4>


In [13]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [47]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [48]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [14]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

<h4> También ahi una función similar a Range pero ocupando: </h4>
<h5 style="color: #12A6E8">arrays=arreglos</h5>

In [17]:
arreglonew = np.arange(1,11)
arreglonew

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [18]:
arreglonew2 = np.arange(1,11,2)
arreglonew2

array([1, 3, 5, 7, 9])

<h3 style = "color:#12A6E8"><b>ALGUNAS FUNCIONES DE NUMPY</b></h3>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [52]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [53]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [54]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [36]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [35]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [37]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:#12A6E8"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:#12E8C0"> haciendo un array aleatorio de 5 elementos </h4>



In [7]:
array_ale = np.random.rand(5)
array_ale

array([0.46233633, 0.60785198, 0.07936329, 0.54850911, 0.98861769])

<h4 style = "color:#12E8C0"> Haciendo una matriz aleatoria de 3x3</h4>
<h5>(n1: filas, n2: columnas)</h5>


In [8]:
matriz = np.random.rand(3,2)
matriz

array([[0.60099344, 0.49763855],
       [0.4968114 , 0.90552414],
       [0.40935745, 0.72826162]])

<h4 style = "color:#12E8C0">arreglo aleatorio de 10 números enteros del 1 al 5</h4>
<h4>(numero uno: numero desde donde empieza, segundo numero: es hasta que numero llega, tercer numero cuantos numero queremos) </h4>


In [9]:
array_ale2  = np.random.randint(1,5,10)
array_ale2

array([2, 3, 3, 1, 3, 4, 4, 3, 1, 1])

<h4 style = "color:#12E8C0"> matriz aleatoria de 10 números enteros del 1 al 100</h4>
<h5>matriz cuadrada (el primer numero es fila, segundo columnas)</h5>


In [10]:
matriz2 = np.random.randint(1,100,(3,5))
matriz2

array([[97,  9, 35, 96,  5],
       [80, 94, 56, 91, 21],
       [45, 98, 39,  4, 68]])